# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from typing import Optional

from src.common.dto.pagination_response_dto import PaginationResponseDto
from src.users.dto.user_create_dto import UserCreateDto, UserUpdateRoleDto
from src.users.dto.user_search_dto import UserSearchDto
from src.users.repository.user_repository import UserRepository
from src.users.user_model import UserModel




from fastapi import Depends
from sqlalchemy.exc import IntegrityError

from src.common.consistency_service import ConsistencyService

class UserService:
    """
    Handles the business logic for user management.
    """

    def __init__(
        self, 
        user_repo: UserRepository = Depends(),
        consistency_service: ConsistencyService = Depends()
    ):
        self.user_repo = user_repo
        self.consistency_service = consistency_service

    async def create_user_if_not_exists(
        self, email: str, name: str, picture: Optional[str]
    ) -> UserModel:
        """
        Retrieves a user by their email. If the user exists, it returns it.
        If the user doesn't exist, it creates a new user document.
        """

        # 1. Check if the user already exists in the database.
        existing_user = await self.user_repo.get_by_email(email)

        if existing_user:
            return existing_user

        # 2. If the user does not exist, create a new User using UserCreateDto
        #    ID will be auto-generated by the DB
        new_user_dto = UserCreateDto(
            email=email,
            name=name,
            picture=picture or "",
        )
        
        # We need to ensure roles are set, but UserCreateDto doesn't have roles.
        # The repository create method takes a Pydantic model or dict.
        # If we pass UserCreateDto, we miss 'roles'.
        # We can pass a dict that includes roles.
        user_data = new_user_dto.model_dump()

        # 3. Call the repository's create() method
        try:
            return await self.user_repo.create(user_data)
        except IntegrityError:
            # Handle race condition: User might have been created by another request
            # between our check and the insert.
            existing_user = await self.user_repo.get_by_email(email)
            if existing_user:
                return existing_user
            raise

    async def get_user_by_id(self, user_id: int) -> Optional[UserModel]:
        """Finds a single user by their ID."""
        return await self.user_repo.get_by_id(user_id)

    async def find_all_users(
        self, search_dto: UserSearchDto, current_user: Optional[UserModel] = None
    ) -> PaginationResponseDto[UserModel]:
        """Retrieves a paginated list of all users."""
        
        # Enforce Org Admin limits if not Super Admin
        if current_user and not current_user.is_super_admin:
            # Get user's admin organizations
            admin_org_ids = [
                org.id for org in current_user.organizations 
                if org.role == "admin" # Check OrganizationRoleEnum.ADMIN value
            ]
            
            if not admin_org_ids:
                # If not admin of any org, return empty or raise forbidden?
                # For now, return empty list to be safe
                return PaginationResponseDto(
                    count=0, page=1, page_size=search_dto.limit, total_pages=0, data=[]
                )

            # If search_dto has organization_id, ensure it's one of the allowed ones
            if search_dto.organization_id:
                if search_dto.organization_id not in admin_org_ids:
                     return PaginationResponseDto(
                        count=0, page=1, page_size=search_dto.limit, total_pages=0, data=[]
                    )
            else:
                # If no specific org requested, filter by ALL admin orgs
                search_dto.organization_ids = admin_org_ids

        return await self.user_repo.query(search_dto)

    async def update_user_role(
        self, user_id: int, role_data: UserUpdateRoleDto
    ) -> Optional[UserModel]:
        """Updates the role of a specific user."""
            
        # Convert the list of enums to a list of strings for DB
        roles_as_strings = role_data.roles

        # The update method in the repository would handle updating the 'role' field
        return await self.user_repo.update(user_id, {"roles": roles_as_strings})

    async def delete_user_by_id(self, user_id: int, current_user: Optional[UserModel] = None) -> bool:
        """Deletes a user from the system."""
        from fastapi import HTTPException, status
        
        if current_user and current_user.id == user_id:
             raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="You cannot delete your own account."
            )
            
        return await self.user_repo.delete(user_id)

    async def update_super_admin_status(self, user_id: int, is_super_admin: bool) -> UserModel:
        """
        Updates the super admin status of a user.
        Syncs the change to both the Database and OpenFGA using ConsistencyService.
        """
        # Import inside method to avoid potential circular imports
        from src.core.fga import fga_client
        from openfga_sdk.client.models import ClientWriteRequest, ClientTuple
        
        # 1. Define DB Operation
        async def db_op() -> UserModel:
            updated_user = await self.user_repo.update(user_id, {"is_super_admin": is_super_admin})
            if not updated_user:
                raise ValueError("User not found")
            return updated_user

        # 2. Define FGA Operation
        async def fga_op():
            if is_super_admin:
                # Write super_admin tuple
                await fga_client.write(ClientWriteRequest(
                    writes=[ClientTuple(
                        user=f"user:{user_id}",
                        relation="super_admin",
                        object="platform:creative-studio"
                    )]
                ))
            else:
                # Remove super_admin tuple
                await fga_client.write(ClientWriteRequest(
                    deletes=[ClientTuple(
                        user=f"user:{user_id}",
                        relation="super_admin",
                        object="platform:creative-studio"
                    )]
                ))

        # 3. Define Rollback Operation
        async def rollback_op():
            # Revert to previous state (negate is_super_admin)
            await self.user_repo.update(user_id, {"is_super_admin": not is_super_admin})

        # 4. Execute via ConsistencyService
        return await self.consistency_service.perform_dual_write(
            db_op=db_op,
            fga_op=fga_op,
            rollback_op=rollback_op,
            error_message="Failed to sync Super Admin status to FGA."
        )
