"""update_org_model_add_logo_and_description

Revision ID: 34c90158bc86
Revises: 22183fcf8e97
Create Date: 2026-01-24 15:01:42.137075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34c90158bc86'
down_revision: Union[str, None] = '22183fcf8e97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('description', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('logo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'logo')
    op.drop_column('organizations', 'description')
    # ### end Alembic commands ###
