"""add_non_nullable_owner_id_to_organizations

Revision ID: 8b45d5a86b86
Revises: 2e855693686f
Create Date: 2026-01-18 23:59:45.460129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b45d5a86b86'
down_revision: Union[str, None] = '2e855693686f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add column as nullable first (so we can backfill)
    op.add_column('organizations', sa.Column('owner_id', sa.Integer(), nullable=True))
    
    # 2. Populate existing rows with a default owner (prefer Super Admin)    
    # If it's a fresh deploy (no orgs), this does nothing (safe).
    # If there are orgs but no users, this sets nothing and the next step will fail (correct, as owner is required).
    op.execute("""
        UPDATE organizations 
        SET owner_id = (
            SELECT id FROM users 
            ORDER BY is_super_admin DESC, id ASC 
            LIMIT 1
        ) 
        WHERE owner_id IS NULL
    """)
    
    # 3. Enforce non-nullable constraint
    op.alter_column('organizations', 'owner_id', nullable=False)
    
    # 4. Create Foreign Key with explicit name
    op.create_foreign_key('organizations_owner_id_fkey', 'organizations', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('organizations_owner_id_fkey', 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'owner_id')
    # ### end Alembic commands ###
